batch_norm: true
batch_size: 256
class_op_size: 22
config: /home/mrx/projects/affinity/ntk_matrix_completion/run_scripts/expts/230131_mt/debug_pool.yml
device: 0
energy_scaler: minmax
energy_type: !!python/object/apply:ntk_matrix_completion.utils.package_matrix.Energy_Type
- 2
epochs: 5
gpu: false
ignore_train: false
input_scaler: standard
l_sizes:
- !!python/tuple
  - 35
  - 18
- !!python/tuple
  - 35
  - 18
load_label:
- load_0
- load_1
- load_2
- load_3
- load_4
- load_5
- load_6
- load_7
- load_8
- load_9
- load_10
- load_11
- load_12
- load_13
- load_14
- load_15
- load_16
- load_17
- load_18
- load_19
- load_20
- load_21
load_scaler: minmax
load_type: load
mask: /home/mrx/projects/affinity_pool/ntk_matrix_completion/data/truths/testing_7/mask_subset.csv
min_delta: 0.5
model: !!python/name:ntk_matrix_completion.models.multitask.multitask_nn.MultiTaskNNSep_v2 ''
optimizer:
  cla_opt: adam
  reg_opt: adam
osda_prior_file: /pool001/mrx/projects/affinity/ntk_matrix_completion/data/priors/221216/iza_all/osda_priors_all.pkl
osda_prior_map: /home/mrx/projects/affinity/ntk_matrix_completion/configs/osda_weights_structural_v2.json
other_prior_to_concat: null
output: /pool001/mrx/projects/affinity/ntk_matrix_completion/output/2023_multitask/multitask_2023224_23572
patience: 3
prior_method: CustomOSDAandZeoliteAsRows
prior_treatment: 3
scheduler: false
seed: 12934
sieved_file: null
softmax: true
split_type: !!python/object/apply:ntk_matrix_completion.utils.utilities.SplitType
- 3
truth: /home/mrx/projects/affinity_pool/ntk_matrix_completion/data/truths/testing_7/truth_subset_ohe.csv
tune: true
zeolite_prior_file: /pool001/mrx/projects/affinity/ntk_matrix_completion/data/priors/zeolite_priors_20221118_25419.pkl
zeolite_prior_map: /home/mrx/projects/affinity/ntk_matrix_completion/configs/zeolite_weights_structural_extendable.json
