output: /home/mrx/projects/binding_energies/ntk_matrix_completion/output/2023_multitask/multitask
config: /home/mrx/projects/binding_energies/ntk_matrix_completion/run_scripts/expts/230123_mt_1.yml
tune: true
gpu: false
split_type: 3
energy_type: 2
input_scaler: standard
energy_scaler: minmax
load_scaler: minmax
ignore_train: false
seed: 12934
truth: /home/mrx/projects/binding_energies/ntk_matrix_completion/data/truths/testing_3/truth.csv
sieved_file: null
mask: /home/mrx/projects/binding_energies/ntk_matrix_completion/data/truths/testing_3/mask.csv
prior_method: CustomOSDAVector
osda_prior_file: /home/mrx/projects/binding_energies/ntk_matrix_completion/data/priors/testing_3/osda_priors_0.pkl
zeolite_prior_file: /home/mrx/projects/binding_energies/ntk_matrix_completion/data/priors/zeolite_priors_20221118_25419.pkl
osda_prior_map: /home/mrx/projects/binding_energies/ntk_matrix_completion/configs/osda_weights_structural_v2.json
zeolite_prior_map: /home/mrx/projects/binding_energies/ntk_matrix_completion/configs/zeolite_weights_structural_extendable.json
other_prior_to_concat: null
prior_method: CustomOSDAVector
prior_treatment: 2
optimizer: 
  cla_opt: adam
  reg_opt: adam
scheduler: false
# debug
epochs: 100
device: cpu
batch_size: 256
model: multitasknnsep
l_sizes: '[(290,16,8,4), (290,16,8,4)]'
# model: multitasknncorr
# l_sizes: '[(290,16), (16,8,4), (16,8,4)]'
# debug please change afterwards