output: /pool001/mrx/projects/affinity/ntk_matrix_completion/output/2023_multitask/multitask
tune: true
gpu: false
split_type: 3
energy_type: 2
input_scaler: standard
energy_scaler: minmax
load_scaler: null
ignore_train: false
seed: 12934
sieved_file: null
truth: /pool001/mrx/projects/affinity/ntk_matrix_completion/data/truths/230212/iza_apriori_zach/2023213_212058_truth_load_norm_ohe.csv
mask: /pool001/mrx/projects/affinity/ntk_matrix_completion/data/truths/230212/iza_apriori_zach/2023213_212058_mask.csv
osda_prior_file: /pool001/mrx/projects/affinity/ntk_matrix_completion/data/priors/221216/iza_all/osda_priors_all.pkl
zeolite_prior_file: /pool001/mrx/projects/affinity/ntk_matrix_completion/data/priors/zeolite_priors_20221118_25419.pkl
osda_prior_map: /home/mrx/projects/affinity/ntk_matrix_completion/configs/osda_weights_structural_v2.json
zeolite_prior_map: /home/mrx/projects/affinity/ntk_matrix_completion/configs/zeolite_weights_structural_extendable.json
other_prior_to_concat: null
prior_method: CustomOSDAandZeoliteAsRows
prior_treatment: 3
# 1 struct, 2 struct and getaway, 3 struct and zeo, 4 getaway and zeo, 5 struct, getaway and zeo
optimizer: 
  cla_opt: adam
  reg_opt: adam
scheduler: false
# debug
epochs: 1000
device: cpu
batch_size: 256
# model: multitasknnsep_v2
# l_sizes: '[(35, 18), (35, 18)]'
# l_sizes: '[(35,16,8,4), (35,16,8,4)]'
# l_sizes: '[(290,16,8,4), (290,16,8,4)]'
model: multitasknncorr_v2
l_sizes: '[(35, 18), (18, 1), (18, 1)]'
# l_sizes: '[(290,16), (16,8,4), (16,8,4)]'
# debug please change afterwards
load_type: load_norm 
# load, load_norm, single
class_op_size: 49
patience: 3
min_delta: 10